# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-05 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_poifavourites'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='POIFavourites',
            new_name='Fav',
        ),
    ]
