# Generated by Django 2.1.2 on 2018-10-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('contactNumber', models.CharField(max_length=15)),
                ('imageFileName', models.CharField(max_length=100)),
                ('lastUpdate', models.DateTimeField()),
            ],
        ),
    ]
